apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
stringData:
  host: "terraform-20251124172253833400000008.c4n0yk4aq9j7.us-east-1.rds.amazonaws.com"
  username: "postgres"
  password: "postgres_password_123"
