apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
stringData:
  host: "clickstream-rds.xxxx.us-east-1.rds.amazonaws.com"
  username: "postgres"
  password: "postgres_password_123"
